//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by n4d.rc
//
#define IDCANCEL2                       3
#define IDI_BOWPAD                      101
#define IDB_EMPTY                       102
#define IDR_MENU                        103
#define IDR_LEXSTYLES                   104
#define IDR_SHORTCUTS                   105
#define IDR_DARKTHEME                   106
#define IDR_SCINTILLAH                  107
#define IDR_AUTOCOMPLETE                108
#define IDD_COMMANDPALETTE              109
#define IDD_FINDREPLACEDLG              110
#define IDD_STYLECONFIGURATOR           111
#define IDD_GOTOLINE                    112
#define IDD_SORTDLG                     113
#define IDD_ABOUTBOX                    114
#define IDD_SETTABWIDTH                 115
#define IDS_ERR_FILETOOBIG              116
#define IDS_NEW_TABTITLE                117
#define IDS_DOYOUWANTOSAVE              118
#define IDS_SAVE                        119
#define IDS_DONTSAVE                    120
#define IDS_CANCEL                      121
#define IDS_HASMODIFICATIONS            122
#define IDS_HOWTOOPENURL                123
#define IDS_GOTOLINEINFO                124
#define IDS_OUTSIDEMODIFICATIONS        125
#define IDS_DOYOUWANTRELOADBUTDIRTY     126
#define IDS_DOYOUWANTTORELOAD           127
#define IDS_SAVELOSTOUTSIDEMODS         128
#define IDS_RELOAD                      129
#define IDS_RELOADLOSTMODS              130
#define IDS_NORELOAD                    131
#define IDS_OUTSIDEREMOVEDHEAD          132
#define IDS_OUTSIDEREMOVED              133
#define IDS_OUTSIDEREMOVEDKEEP          134
#define IDS_OUTSIDEREMOVEDCLOSE         135
#define IDS_FINDRETRYWRAP               136
#define IDS_FINDNOTFOUND                137
#define IDS_ACCESS_ELEVATE              138
#define IDS_ACCESS_ASK_ELEVATE          139
#define IDS_ELEVATEOPEN                 140
#define IDS_DONTELEVATEOPEN             141
#define IDS_ELEVATESAVE                 142
#define IDS_DONTELEVATESAVE             143
#define IDS_NOFUNCTIONSFOUND            144
#define IDR_BOWPADUIH                   145
#define IDS_FINDRESULT_HEADERFILE       146
#define IDS_FINDRESULT_HEADERLINE       147
#define IDS_FINDRESULT_HEADERLINETEXT   148
#define IDS_REGEXTOOLTIP                149
#define IDS_REGEX_OK                    150
#define IDS_REGEX_NOTOK                 151
#define IDS_FINDALL                     152
#define IDS_FINDALLINTABS               153
#define IDS_REPLACEALL                  154
#define IDS_FILE_DOESNT_EXIST           155
#define IDS_FILE_ASK_TO_CREATE          156
#define IDS_FILE_CREATE                 157
#define IDS_FILE_CREATE_CANCEL          158
#define IDS_RELOADREALLY                159
#define IDS_DORELOAD                    160
#define IDS_DONTRELOAD                  161
#define IDS_REPLACEALLINSELECTION       162
#define IDS_FAILEDTOLOADFILE            163
#define IDS_COPYTITLE                   164
#define IDS_FILEDELETE_TITLE            165
#define IDS_FILEDELETE_ASK              166
#define IDS_FILEDELETE_DEL              167
#define IDS_FILEDELETE_CANCEL           168
#define IDS_REPLACEALLINTABS            169
#define IDS_STATUSTTDOCSIZE             170
#define IDS_STATUSTTCURPOS              171
#define IDS_STATUSTTEOL                 172
#define IDS_STATUSTTTYPING              173
#define IDS_STATUSTTTYPINGOVL           174
#define IDS_STATUSTTTYPINGINS           175
#define IDS_STATUSTTTABS                176
#define IDS_FILEISREADONLY              177
#define IDS_FILEMAKEWRITABLEASK         178
#define IDS_EDITFILE                    179
#define IDS_KEEPREADONLY                180
#define IDS_FAILEDTOSAVEFILE            181
#define IDS_ELEVATED                    182
#define IDS_USER_INCLUDES               183
#define IDS_SYSTEM_INCLUDES             184
#define IDS_NO_FILES_FOUND              185
#define IDS_FINDRESULT_COUNT            186
#define IDS_FINDRESULT_COUNTALL         187
#define IDS_STATUSSELECTION             188
#define IDS_STATUSTTTABSPACES           189
#define IDS_STATUSTTENCODING            190
#define IDS_STATUSZOOM                  191
#define IDS_FINDALLINDIR                192
#define IDS_SEARCHING_FILE              193
#define IDS_DOITFORALLFILES             194
#define IDS_FILE_DROP                   195
#define IDS_FILE_DROP_COPY              196
#define IDS_FILE_DROP_MOVE              197
#define IDS_FILE_DROP_DOCOPY            198
#define IDS_FILE_DROP_DOMOVE            199
#define IDS_FILE_DROP_CANCEL            200
#define IDS_REPLACEDCOUNT               201
#define IDS_FINDFILES                   202
#define IDS_NOSEARCHFOLDER              203
#define IDS_SEARCHFOLDERNOTFOUND        204
#define IDS_TT_SETSEARCHFOLDERTOPARENT  205
#define IDS_TT_SETSEARCHFOLDERCURRENT   206
#define IDS_TT_SETSEARCHFOLDER          207
#define IDS_TT_FINDPREVIOUS             208
#define IDS_PLEASEWAIT                  209
#define IDS_NOFUNCTIONFINDORREPLACE     210
#define IDS_NOMORETOREPLACE             211
#define IDS_SEARCHFILESLABEL            212
#define IDS_SEARCHFOLDERLABEL           213
#define IDS_FILELOADING_TITLE           214
#define IDS_SEARCHING_FILE_MAX          215
#define IDS_STATUS_CURPOS               216
#define IDS_STATUS_CURPOSLONG           217
#define IDS_STATUSSELECTIONLONG         218
#define IDS_STATUSSELECTIONNONE         219
#define IDS_EXTENSIONTOOLTIP            220
#define IDS_STATUSTTR2L                 221
#define IDS_FOLDTEXT                    222
#define IDS_CUSTOMCOMMANDTITLE          223
#define IDS_IMPORTBPLEX_TITLE           224
#define IDS_IMPORTBPLEX_QUESTION        225
#define IDS_IMPORTBPLEX_IMPORT          226
#define IDS_IMPORTBPLEX_OPEN            227
#define IDS_COMMANDPALETTE_FILTERCUE    228
#define IDS_SELECTENCODING_FILTERCUE    229
#define IDS_SELECTLEXER_FILTERCUE       230
#define IDS_APP_TITLE                   231
#define IDS_SELECTTAB_FILTERCUE         232
#define IDB_QUICKBAR_DARK               267
#define IDB_QUICKBAR_LIGHT              268
#define IDC_BOWPAD                      300
#define IDC_FINDBTN                     301
#define IDC_REPLACECOMBO                302
#define IDC_REPLACEBTN                  303
#define IDC_REPLACEALLBTN               304
#define IDC_REPLACEALLINTABSBTN         305
#define IDC_MATCHWORD                   306
#define IDC_MATCHCASE                   307
#define IDC_MATCHREGEX                  308
#define IDC_UNDERLINECHECK              309
#define IDC_FUNCTIONS                   310
#define IDC_SEARCHSUBFOLDERS            311
#define IDC_SEARCHFILES                 312
#define IDC_LANGCOMBO                   313
#define IDC_STYLECOMBO                  314
#define IDC_SEARCHFOLDERFOLLOWTAB       315
#define IDC_FG_BTN                      316
#define IDC_FINDRESULTSACTION           317
#define IDC_BK_BTN                      318
#define IDC_FONTCOMBO                   319
#define IDC_FONTSIZECOMBO               320
#define IDC_BOLDCHECK                   321
#define IDC_ITALICCHECK                 322
#define IDC_EXTENSIONS                  323
#define IDC_LINE                        324
#define IDC_SEARCHCOMBO                 325
#define IDC_SEARCHINFO                  326
#define IDC_LINEINFO                    327
#define IDC_VERSIONLABEL                328
#define IDC_WEBLINK                     329
#define IDC_FINDALL                     330
#define IDC_FINDALLINTABS               331
#define IDC_FINDRESULTS                 332
#define IDC_FINDALLINDIR                333
#define IDC_SETSEARCHFOLDER             334
#define IDC_R_ANSI                      335
#define IDC_SEARCHFOLDER                336
#define IDC_SETSEARCHFOLDERTOPARENT     337
#define IDC_FINDFILES                   338
#define IDC_SETSEARCHFOLDERCURRENT      339
#define IDC_SORTDLG_ORDER               340
#define IDC_SORTDLG_NUM_CHECK           341
#define IDC_SORTDLG_CASE_CHECK          342
#define IDC_FINDPREVIOUS                343
#define IDC_SEARCHFORLABEL              344
#define IDC_FINDPREVIOUS2               344
#define IDC_REPLACEWITHLABEL            345
#define IDC_SORTORDERLABEL              346
#define IDC_SCINTILLA                   347
#define IDC_REMOVEDUPLICATES            348
#define IDC_FILTER                      349
#define IDC_RESULTS                     350
#define IDC_HIDE                        351
#define IDC_HIGHLIGHT                   352
#define IDC_SAVE                        353
#define IDC_SNIPPETLIST                 354
#define IDC_DELETE                      355
#define IDC_SNIPPETNAME                 356
#define IDC_TABWIDTH                    357
#define IDC_SORTDLG_ORDER_CHECK         358
#define cmdNothing                      30000
#define cmdCommandPalette               30001
#define cmdExit                         30002
#define cmdNew                          30003
#define cmdNewDefault                   30004
#define cmdOpen                         30005
#define cmdSave                         30006
#define cmdSaveAll                      30007
#define cmdSaveAuto                     30008
#define cmdSaveAs                       30009
#define cmdClose                        30010
#define cmdCloseAll                     30011
#define cmdWriteProtect                 30012
#define cmdCopy                         30013
#define cmdCut                          30014
#define cmdPaste                        30015
#define cmdPasteHtml                    30016
#define cmdUndo                         30017
#define cmdRedo                         30018
#define cmdLineWrap                     30019
#define cmdWhiteSpace                   30020
#define cmdLinenumbers                  30021
#define cmdFileTree                     30022
#define cmdOpenFolder                   30023
#define cmdFoldCurrent                  30024
#define cmdEOLWin                       30025
#define cmdEOLUnix                      30026
#define cmdEOLMac                       30027
#define cmdPrevNext                     30028
#define cmdPrevious                     30029
#define cmdNext                         30030
#define cmdFindFile                     30031
#define cmdFindReplace                  30032
#define cmdFindNext                     30033
#define cmdFindPrev                     30034
#define cmdFindSelectedNext             30035
#define cmdFindSelectedPrev             30036
#define cmdDelete                       30037
#define cmdSelectAll                    30038
#define cmdStyleConfigurator            30039
#define cmdVerticalEdge                 30040
#define cmdComment                      30041
#define cmdUnComment                    30042
#define cmdUppercase                    30043
#define cmdLowercase                    30044
#define cmdTitlecase                    30045
#define cmdTabSize                      30046
#define cmdUseTabs                      30047
#define cmdLineDuplicate                30048
#define cmdLineSplit                    30049
#define cmdLineJoin                     30050
#define cmdLineUp                       30051
#define cmdLineDown                     30052
#define cmdSort                         30053
#define cmdEditSelection                30054
#define cmdPrintNow                     30055
#define cmdPrint                        30056
#define cmdPageSetup                    30057
#define cmdGotoLine                     30058
#define cmdGotoSymbol                   30059
#define cmdWhitespacecombo              30060
#define cmdTrim                         30061
#define cmdTabs2Spaces                  30062
#define cmdSpaces2Tabs                  30063
#define cmdReload                       30064
#define cmdBookmarks                    30065
#define cmdBookmarkToggle               30066
#define cmdBookmarkClearAll             30067
#define cmdBookmarkNext                 30068
#define cmdBookmarkPrev                 30069
#define cmdToggleTheme                  30070
#define cmdLaunchEdge                   30071
#define cmdLaunchSciter                 30072
#define cmdLaunchFirefox                30073
#define cmdLaunchChrome                 30074
#define cmdLaunchSciterDebug            30075
#define cmdLaunchInspector              30076
#define cmdLaunchExplorer               30077
#define cmdLaunchConsole                30078
#define cmdFunctions                    30079
#define cmdCloseAllButThis              30080
#define cmdCopyPath                     30081
#define cmdCopyName                     30082
#define cmdCopyDir                      30083
#define cmdSelectEncoding               30084
#define cmdEnableD2D                    30085
#define cmdConfigShortcuts              30086
#define cmdAutoBraces                   30087
#define cmdOpenSelection                30088
#define cmdFileDelete                   30089
#define cmdTabListDropdownMenu          30090
#define cmdHighlightBrace               30091
#define cmdFoldingMargin                30092
#define cmdFoldAll                      30093
#define cmdLineWrapIndent               30094
#define cmdAutocomplete                 30095
#define cmdConfigStyle                  30096
#define cmdAutocMatchcase               30097
#define cmdZoom100                      30098
#define cmdZoomIn                       30099
#define cmdZoomOut                      30100
#define cmdAbout                        30101
#define cmdGotoBrace                    30102
#define cmdCutPlain                     30103
#define cmdCopyPlain                    30104
#define cmdSessionLast                  30105
#define cmdPasteHistory                 30106
#define cmdFrameCaretLine               30107
#define cmdSelectLexer                  30108
#define cmdShowAutoComplete             30109
#define cmdSelectTab                    30110
#define cmdOpenRecent                   30111
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        269
#define _APS_NEXT_COMMAND_VALUE         32896
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
